version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # Port pour les services LocalStack
      - "4512:4510" # Port pour les logs
    environment:
      - PERSISTENCE=true
    volumes:
      - localstack-data:/var/lib/localstack
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  localstack-data:









